name: Update README

on:
  schedule:
    - cron: "0 7 * * *" # Runs every day at 7 AM UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: anuraghazra/github-readme-stats@master
      - uses: jamesgeorge007/github-activity-readme@v0.1.1
