name: Update Skills

on:
  schedule:
    - cron: "0 9 * * *" # Runs every day at 9 AM UTC
  workflow_dispatch:

jobs:
  update-skills:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Analyze Skills from Repositories
        id: skills
        run: |
          repos=$(curl -s "https://api.github.com/users/Sarvesh1814/repos?per_page=100")
          languages=$(echo "$repos" | jq -r '.[] | .language' | sort | uniq -c | sort -nr | awk '{print $2}')
          skill_list=$(echo "$languages" | sed ':a;N;$!ba;s/\n/- /g')
          echo "skill_list=$skill_list" >> $GITHUB_ENV

      - name: Update Skills in README
        run: |
          sed -i "/<!--START_SECTION:skills-->/,/<!--END_SECTION:skills-->/c\<!--START_SECTION:skills-->\n- $skill_list\n<!--END_SECTION:skills-->" README.md

      - name: Commit changes
        run: |
          git config --global user.name "Sarvesh1814"
          git config --global user.email "sbagwe9@gmail.com"
          git add README.md
          git commit -m "Update Skills dynamically"
          git push
